// Auto generated by utensor-cli

#ifndef __MODELS_DNN_MODEL_H
#define __MODELS_DNN_MODEL_H
#include "uTensor/core/context.hpp"
void get_DNN_model_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_DNN_MODEL_H